apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: login-service
        image: login-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-login:3306/login_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT-5"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "uptc2026"
